### ISSUE TITLE
音乐下载之后跳转到“我的音乐库”，歌曲列表不会更新

### ISSUE THREAD

**Issue by mstouk57g** [AZ-Studio-2023/AZMusicDownloader#1]
![image](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/65524880/2dba76db-ca54-44ff-bd56-c9a1670bd7ad)
![image](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/65524880/9825d044-8068-4592-9fc9-5027b451c551)
![image](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/65524880/4eb7ae4f-dfe3-4be2-9a1f-45ebfef215bc)
@zlk-sys 
音乐下载之后跳转到“我的音乐库”，歌曲列表不会更新
需要你修复
应该在切换页面的时候重新加载列表

**Comment by zlk-sys** [comment]
问题反馈收到，将在下一个版本解决
