### ISSUE TITLE
下载链接缺失

### ISSUE THREAD

**Issue by WAusar** [AZ-Studio-2023/AZMusicDownloader#2]
[v2.3.0]免安装

![image](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/35913438/b9353cb6-a4ba-4b0a-8292-e22faa64195c)

**Comment by zlk-sys** [comment]
检查一下网络环境是否正常，或着换一首歌看看能不能下载

**Comment by minazuki2022** [comment]
我也遇到同样的问题，换了好几首歌都一样，偶尔才有一个能下载成功

**Comment by zlk-sys** [comment]
估计是api服务器取不到音乐链接，有可能是被风控了，我这里用着都能下载
