### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Yzcloud** [AZ-Studio-2023/AZMusicDownloader#3]
![photo_2024-06-08_18-37-31](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/88927779/25e2c2ab-7179-48cb-8e39-292c615a34ed)

**Comment by zlk-sys** [comment]
检查网络状况 以及是否开启代理服务

**Comment by Yzcloud** [comment]
> 检查网络状况 以及是否开启代理服务

网络正常的，代理开不开都不行，晚点在试试

**Comment by zlk-sys** [comment]
![屏幕截图 2024-06-12 210854](https://github.com/AZ-Studio-2023/AZMusicDownloader/assets/76240341/0de947cd-3371-40d1-a57e-bb51bffd0f24)
我这边使用是正常的

**Comment by mstouk57g** [comment]
唔~
上来搜索就报错误欸
您那边解决了吗？或许我可以帮助你：
如果是用的网易云音乐（API选的是NCMA），请尝试访问 http://ncma.azprod.cn/ 这个地址一下，ping也行，看看通不通
因为NCMA的API用的是这个地址
至于QQ音乐，额，如果是再说。。。。。。。

**Comment by Yzcloud** [comment]
谢谢，我用虚拟机可以用了

**Comment by mstouk57g** [comment]
OKOK
感谢支持～
如果没有问题，那么可以关闭issue了
有任何疑问欢迎继续提issue
