### ISSUE TITLE
表格中信息显示不全

### ISSUE THREAD

**Issue by martjay** [AZ-Studio-2023/AZMusicDownloader#5]
![xxxxxx](https://github.com/user-attachments/assets/eac2f1d9-60c6-46e2-a5de-aa890588d4e1)

除了这个问题外，我想提个建议，增加flac无损和aac格式的下载，哎呀mp3音质真的没有这2个好

**Comment by mstouk57g** [comment]
之前没有遇到这个问题呢。我们尽快看看

**Comment by zlk-sys** [comment]
收到 
这个好像是因为在旧版本中某些设备遇到歌曲名长会使表格组件显示出错做的一个短显示功能
会在下一个版本修复

**Comment by zlk-sys** [comment]
其实吧，我代码里将保存后缀名改成flac你们可能就会以为是无损了
取到的音频链接是不带后缀名的，所以统一保存为mp3

有关显示不全的问题，已解决，将在下一个版本发布

**Comment by martjay** [comment]
> 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> 
> 有关显示不全的问题，已解决，将在下一个版本发布

兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了

**Comment by zlk-sys** [comment]
> > 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> > 有关显示不全的问题，已解决，将在下一个版本发布
> 
> 兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了

呃，你没有仔细阅读我之前的回复吧。NCMA那边免费能取到的就是普通音质，虽然我没看他源码（现在也删库了），但是大概原理就是去拿你在客户端听的音乐的URL，你免费能听到什么，拿到的就是什么。都是免费的，还得寸进尺要无损。。现在这项目没被封就不错了

**Comment by martjay** [comment]
> > > 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> > > 有关显示不全的问题，已解决，将在下一个版本发布
> > 
> > 
> > 兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了
> 
> 呃，你没有仔细阅读我之前的回复吧。NCMA那边免费能取到的就是普通音质，虽然我没看他源码（现在也删库了），但是大概原理就是去拿你在客户端听的音乐（免费能播放的歌）的URL，你免费能听到什么，拿到的就是什么。都是免费的，还得寸进尺要无损。。现在这项目没被封就不错了。这项目适用于下载可以免费听但不能免费下载的音乐（当然能免费下载的歌也可以下

还得寸进尺，我就问了个问题而已，你知道可以说不知道可以不说，不要胡乱揣测别人心里，我用另一个下无损了，得寸进尺的我也不跟你分享了

**Comment by zlk-sys** [comment]
> > > > 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> > > > 有关显示不全的问题，已解决，将在下一个版本发布
> > > 
> > > 
> > > 兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了
> > 
> > 
> > 呃，你没有仔细阅读我之前的回复吧。NCMA那边免费能取到的就是普通音质，虽然我没看他源码（现在也删库了），但是大概原理就是去拿你在客户端听的音乐（免费能播放的歌）的URL，你免费能听到什么，拿到的就是什么。都是免费的，还得寸进尺要无损。。现在这项目没被封就不错了。这项目适用于下载可以免费听但不能免费下载的音乐（当然能免费下载的歌也可以下
> 
> 还得寸进尺，我就问了个问题而已，你知道可以说不知道可以不说，不要胡乱揣测别人心里，我用另一个下无损了，得寸进尺的我也不跟你分享了

我明白你对音质的追求。不过，正如我之前提到的，目前这个项目的功能是基于免费音质的资源，实际上也并没有涉及破解或修改音乐平台的操作，所有下载的内容都是在平台允许的范围内获取的。无损音质确实需要VIP账号或相关付费服务支持，项目本身的目的也是为那些可以免费听到但不能直接下载的歌曲提供一个便捷的下载方式。既然已有能绕过限制破解出flac格式音乐，那为何还这么麻烦来提出这个issue？至于我为什么说“得寸进尺”，前面也说过了这项目存活本来就存在风险，很容易就被某平台投诉，继续开发出更高音质下载岂不是得进局子？这风险又不是你来承担，你就只是来提一个issue，我肯定是不能冒这么大险开发的啊

**Comment by martjay** [comment]
> > > > > 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> > > > > 有关显示不全的问题，已解决，将在下一个版本发布
> > > > 
> > > > 
> > > > 兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了
> > > 
> > > 
> > > 呃，你没有仔细阅读我之前的回复吧。NCMA那边免费能取到的就是普通音质，虽然我没看他源码（现在也删库了），但是大概原理就是去拿你在客户端听的音乐（免费能播放的歌）的URL，你免费能听到什么，拿到的就是什么。都是免费的，还得寸进尺要无损。。现在这项目没被封就不错了。这项目适用于下载可以免费听但不能免费下载的音乐（当然能免费下载的歌也可以下
> > 
> > 
> > 还得寸进尺，我就问了个问题而已，你知道可以说不知道可以不说，不要胡乱揣测别人心里，我用另一个下无损了，得寸进尺的我也不跟你分享了
> 
> 我明白你对音质的追求。不过，正如我之前提到的，目前这个项目的功能是基于免费音质的资源，实际上也并没有涉及破解或修改音乐平台的操作，所有下载的内容都是在平台允许的范围内获取的。无损音质确实需要VIP账号或相关付费服务支持，项目本身的目的也是为那些可以免费听到但不能直接下载的歌曲提供一个便捷的下载方式。既然已有能绕过限制破解出flac格式音乐，那为何还这么麻烦来提出这个issue？至于我为什么说“得寸进尺”，前面也说过了这项目存活本来就存在风险，很容易就被某平台投诉，继续开发出更高音质下载岂不是得进局子？这风险又不是你来承担，你就只是来提一个issue，我肯定是不能冒这么大险开发的啊

哥们，你净瞎操心呢，如果说会员音乐也能下载，就算也是侵权的，不管你是mp3还是无损。我是后来找到的无损下载的，我知道现在查的严，所以挺珍惜的。这玩意出来本来就是为了下盗版的，要说什么侵不侵权我觉得就有点过了。

**Comment by mstouk57g** [comment]
无法下载无损音乐是NCMA的限制
或许我们还没有找到正解
可能后续我们会更新这些功能
但这不是讨论「版权」问题的地方

**Comment by zlk-sys** [comment]
> > > > > > 取到的音频链接是不带后缀名的，所以统一保存为mp3。就算怎么改，音质也是一样的。无损音质的话，需要登录VIP账号，毕竟这玩意只是一个API客户端，本程序无任何破解音乐平台的操作。
> > > > > > 有关显示不全的问题，已解决，将在下一个版本发布
> > > > > 
> > > > > 
> > > > > 兄弟，真无损跟MP3区别还是很大的，虽然说320kbps已经挺好了，但是aac文件不大也比MP3更好，flac就更不用说了
> > > > 
> > > > 
> > > > 呃，你没有仔细阅读我之前的回复吧。NCMA那边免费能取到的就是普通音质，虽然我没看他源码（现在也删库了），但是大概原理就是去拿你在客户端听的音乐（免费能播放的歌）的URL，你免费能听到什么，拿到的就是什么。都是免费的，还得寸进尺要无损。。现在这项目没被封就不错了。这项目适用于下载可以免费听但不能免费下载的音乐（当然能免费下载的歌也可以下
> > > 
> > > 
> > > 还得寸进尺，我就问了个问题而已，你知道可以说不知道可以不说，不要胡乱揣测别人心里，我用另一个下无损了，得寸进尺的我也不跟你分享了
> > 
> > 
> > 我明白你对音质的追求。不过，正如我之前提到的，目前这个项目的功能是基于免费音质的资源，实际上也并没有涉及破解或修改音乐平台的操作，所有下载的内容都是在平台允许的范围内获取的。无损音质确实需要VIP账号或相关付费服务支持，项目本身的目的也是为那些可以免费听到但不能直接下载的歌曲提供一个便捷的下载方式。既然已有能绕过限制破解出flac格式音乐，那为何还这么麻烦来提出这个issue？至于我为什么说“得寸进尺”，前面也说过了这项目存活本来就存在风险，很容易就被某平台投诉，继续开发出更高音质下载岂不是得进局子？这风险又不是你来承担，你就只是来提一个issue，我肯定是不能冒这么大险开发的啊
> 
> 哥们，你净瞎操心呢，如果说会员音乐也能下载，就算也是侵权的，不管你是mp3还是无损。我是后来找到的无损下载的，我知道现在查的严，所以挺珍惜的。这玩意出来本来就是为了下盗版的，要说什么侵不侵权我觉得就有点过了。

好像我似乎并未说过该软件是能下载会员音乐的，只是说免费音乐限制下载的可以下。不能完整听的还是不能听。你觉得侵权太过了，那只是你站在使用者的角度来看，毕竟官司到不了你头上。开源社区始终是一个很好的学习交流平台，而不是能规避法律的借口。
