### ISSUE TITLE
标题文字显示不全

### ISSUE THREAD

**Issue by martjay** [AZ-Studio-2023/AZMusicDownloader#6]
![xxxxxx](https://github.com/user-attachments/assets/eac2f1d9-60c6-46e2-a5de-aa890588d4e1)

除了这个问题外，我想提个建议，增加flac无损和aac格式的下载，哎呀mp3音质真的没有这2个好

**Comment by mstouk57g** [comment]
与#5重复了，请移步至#5

**Comment by mstouk57g** [comment]
aac和flac可能做不到
因为下载器本质是解析音乐平台的音频文件来下载
但目前实际情况是只能弄到mp3的链接？
