### ISSUE TITLE
使用自建API并登录VIP账号后，下载VIP歌曲仍然只有30s

### ISSUE THREAD

**Issue by DangoPie** [AZ-Studio-2023/AZMusicDownloader#7]
本地部署NeteaseMusicAPI，启动并登录VIP账号后，将http://localhost:3000/作为NCMA地址，下载VIP歌曲依旧只有30s

**Comment by zlk-sys** [comment]
不是很确定接口是否还能使用 
毕竟这玩意依赖于[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)，而原项目已经被警告下架了
如果还能使用的话会尽力完善的

**Comment by DangoPie** [comment]
补充一点，我用的NeteaseCloudMusicApi是这个项目，大佬可以试试Orz
https://www.npmjs.com/package/NeteaseCloudMusicApi?activeTab=readme
大佬加油，感谢付出

**Comment by zlk-sys** [comment]
![Q1](https://github.com/user-attachments/assets/0651aa9d-3507-4234-b728-2dbfc6a2f3c6)
已经做好了，已提交至Beta仓库，将在下一个版本发布
